<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP-ENVY" failures="1" tests="10" name="org.automation.ui.BlazeDemoTests" time="105.270" errors="0" timestamp="2025-10-01T17:29:49 IST" skipped="0">
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testHomePageTitle" time="9.170">
    <failure message="expected [WrongTitle] but found [BlazeDemo]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [WrongTitle] but found [BlazeDemo]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.automation.ui.BlazeDemoTests.testHomePageTitle(BlazeDemoTests.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- testHomePageTitle -->
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testFlightSelectionPage" time="9.511"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testHomePageContainsDepartureAndDestination" time="10.020"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testNavigateToHomePage" time="9.926"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testPurchasePageContainsForm" time="10.365"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testConfirmationPage" time="10.908"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testSelectFirstFlight" time="11.007"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testFlightSearchNavigation" time="10.658"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testPurchaseFlight" time="11.832"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testFillPurchaseForm" time="11.873"/>
</testsuite> <!-- org.automation.ui.BlazeDemoTests -->
